### ISSUE TITLE
2.1.3 Click Pictures

### ISSUE THREAD

**Issue by dazz10** [Tech-Makers/road_crack#3]
Camera is not working properly, it is not scanning pictures.
Please fix the issue in the application.

**Comment by Vshree61** [comment]
We are implementing the code, we will complete the updation very soon.

**Comment by Vshree61** [comment]
I have uploaded the code for this issue. Refer to this link for the code [Android Application](https://github.com/Tech-Makers/CDS) . 
The camera is working properly now and is scanning pictures.

**Comment by dazz10** [comment]
Fix verified, its working now.
